/**
 * FANTASTICON ICON FONT GENERATOR
 *
 * This file generates icon fonts from SVG files using Fantasticon.
 *
 * ONLY MODIFY THIS FILE IF ABSOLUTELY NECESSARY.
 *
 * Usage: yarn build:icons
 */

import { type RunnerOptions, FontAssetType, generateFonts, OtherAssetType } from 'fantasticon'
import fs from 'node:fs'
import path from 'node:path'

const GENERATED_FONTS_FOLDER = './src/assets/generated/fonts'

const ICONS_FOLDER = './assets/icons'

const AUTO_GENERATED_COMMENT_LINES = [
  '=================================================================',
  '   AUTO-GENERATED FILE. DO NOT EDIT.',
  '   This file was generated by Fantasticon icon font generator.',
  '=================================================================',
]

const GENERIC_COMMENT = `/*\n${AUTO_GENERATED_COMMENT_LINES.join('\n')}\n*/\n`

const COMMENT_TEMPLATES: Record<string, string> = {
  '.ts': GENERIC_COMMENT,
  '.css': GENERIC_COMMENT,
}

const fantasticonConfig: RunnerOptions = {
  inputDir: path.resolve(ICONS_FOLDER),
  outputDir: path.resolve(GENERATED_FONTS_FOLDER),

  // --- FONT NAMING ---

  // Font family name and base filename for generated files
  name: 'icons',

  // --- OUTPUT FORMATS ---

  // Font file formats to generate - WOFF2 for modern browsers
  fontTypes: [FontAssetType.WOFF],

  // Additional files to generate - CSS classes and TypeScript enum
  assetTypes: [OtherAssetType.CSS, OtherAssetType.TS],

  // --- CSS CONFIGURATION ---

  // Prefix for icon class names (home.svg → home)
  prefix: 'icon-',
  // Base CSS selector for icon font styles
  selector: '.icon',

  // --- FONT OPTIMIZATION ---

  // Internal coordinate system height (1000 = standard precision)
  fontHeight: 1000,
  // Distance below baseline (0 = perfect text alignment)
  descent: 0,
  // Auto-scale all icons to consistent size
  normalize: true,
}

/**
 * Ensures that the specified output directory exists. If it does not exist, it will be created.
 *
 * @param dirPath - The path to the directory to check or create.
 * @returns A promise that resolves when the directory exists or is created.
 */
const createOutputDirectory = async (dirPath: string): Promise<void> => {
  try {
    await fs.promises.access(dirPath).catch(async () => {
      await fs.promises.mkdir(dirPath, { recursive: true })
      console.log(`📁 Created output directory: ${dirPath}`)
    })
    console.log(`📁 Output directory exists: ${dirPath}`)
  }
  catch (error) {
    console.error(`❌ Failed to create output directory: ${dirPath}`)
    console.error(error instanceof Error ? error.message : 'Unknown error occurred')
    process.exit(1)
  }
}

/**
 * Generates icon font files from SVGs using the Fantasticon API.
 * Ensures the output directory exists, then runs the font generation process.
 * Logs progress and handles errors.
 *
 * @returns A promise that resolves when the icon font files are generated.
 */
const buildIconFontFiles = async (): Promise<void> => {
  console.log('🎨 Generating icon font with Fantasticon API...')
  console.log(`📁 Input: ${fantasticonConfig.inputDir}`)
  console.log(`📁 Output: ${fantasticonConfig.outputDir}`)

  // Ensure output directory exists
  await createOutputDirectory(fantasticonConfig.outputDir)

  try {
    const result = await generateFonts(fantasticonConfig)

    console.log('✅ Icons generated successfully!')

    // Show what was generated
    const iconCount = Object.keys(result.codepoints || {}).length

    console.log(`📊 Generated ${iconCount} icons`)
    console.log(`📁 Check output in: ${fantasticonConfig.outputDir}`)
  }
  catch (error) {
    console.error('❌ Icon generation failed:')

    if (error instanceof Error) {
      console.error(error.message)
    }
    else {
      console.error('Unknown error occurred')
    }

    process.exit(1)
  }
}

/**
 * Adds auto-generated file comments to the top of each generated font file (CSS, TS) in the output folder.
 * Skips files that do not match the supported extensions or already contain the comment.
 *
 * @returns A promise that resolves when comments are added to all relevant files.
 */
const addCommentsToAutoGeneratedFolderFiles = async (): Promise<void> => {
  const folder = GENERATED_FONTS_FOLDER

  try {
    const files = await fs.promises.readdir(folder)

    await Promise.all(files.map(async (file) => {
      const ext = path.extname(file)

      const comment = COMMENT_TEMPLATES[ext]

      if (!comment) {
        return
      }

      const filePath = path.join(folder, file)

      const content = await fs.promises.readFile(filePath, 'utf8')

      if (!content.startsWith(comment)) {
        await fs.promises.writeFile(filePath, comment + content, 'utf8')
        console.log(`📝 Added comment to ${file}`)
      }
    }))
  }
  catch (error) {
    console.error('❌ Failed to read the generated fonts folder:')
    console.error(error instanceof Error ? error.message : 'Unknown error occurred')
  }
}

// Run the build
buildIconFontFiles().then(async () => {
  await addCommentsToAutoGeneratedFolderFiles()
})
